### ISSUE TITLE
D3D9 and GL don't support instancing

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#10]
Intended behavior (D3D11):
![image](https://github.com/lrre-foss/rnr/assets/133731034/7e3952f2-1bda-4cba-9347-59bf6bd8d6ab)
Actual behavior (D3D9):
![image](https://github.com/lrre-foss/rnr/assets/133731034/87f2cd10-68ee-417e-bdb9-3e9df10126c1)

**Comment by rjindael** [comment]
@floralrainfall

**Comment by sorket** [comment]
Instancing has been replaced with Static Geometry.
