### ISSUE TITLE
Resizing the window with D3D9 causes the 3D view to go black

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#11]

**Comment by ElCapor** [comment]
Reset the driver on window reset maybe , just a suggestion though

**Comment by sorket** [comment]
> Reset the driver on window reset maybe , just a suggestion though

I believe OGRE tries to do this. The logs report the driver was recovered successfully, but the scene is entirely black. Currently, nobody has pushed to resolve this as of recent.

**Comment by rjindael** [comment]
can we just ditch DirectX support entirely..? this project was meant to be GL-exclusive initially

**Comment by sorket** [comment]
> can we just ditch DirectX support entirely..? this project was meant to be GL-exclusive initially

This'll make me sad. We should consult OGRE forums before giving this up.
Also, if we do this, the only thing that'll work is GL. None of the other options.

**Comment by rjindael** [comment]
D3D9 support has been dropped entirely, rendering this issue invalid.
