### ISSUE TITLE
issues with linux fedora (nobara)

### ISSUE THREAD

**Issue by TouseefX** [lrre-foss/rnr#118]
when i am at 99% almost making it

it says this

[99%] Linking CXX executable rnr-client
/usr/bin/ld: cannot find -lglm: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rnr-client.dir/build.make:145: rnr-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:227: CMakeFiles/rnr-client.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

this error is from glm missing dlls but glm nerver had a dll in their new verison and idk how to go back to their old verison

**Comment by floralrainfall** [comment]
Try changing line 85 of CMakeLists.txt to glm::glm rather then glm

**Comment by TouseefX** [comment]
there is no glm on that line?

**Comment by TouseefX** [comment]
thank you it worked the glm was at line 80

**Comment by TouseefX** [comment]
btw on linux is like gray screen and then it shows up
