### ISSUE TITLE
Only D3D9 and GL rendering options are functional

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#14]
There are no errors in logs to explain why this is happening. This is a mystery that needs to be solved ASAP.

**Comment by floralrainfall** [comment]
GL3+ (and I assume DX11) should work if the BrickColor system has proper shaders; the error with using BrickColor on GL3+ is that the materials created by the BrickColor system are purely using the fixed-function pipeline, and are not being recompiled by RTShader::ShaderGenerator.

**Comment by sorket** [comment]
This is still a mystery. Rendering options are still essentially screwed and I don't know why and don't care to figure out why at the moment. Adding "help wanted" to this issue.

**Comment by sorket** [comment]
It's because it couldn't find shaders hidden in a directory. lol
