### ISSUE TITLE
Add ContentProvider, ContentId, TextureId

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#17]

**Comment by rjindael** [comment]
All yours king

**Comment by sorket** [comment]
> All yours king

`SSB3aWxsIGdpdmUgeW91IG1vcmUgcGFpbiB0aGFuIHlvdSBjYW4gaW1hZ2luZS4gWW91ciBicmFpbnMgd2lsbCBsZWFrIG91dCBvZiB5b3VyIGVhcnMsIGFuZCB5b3VyIGJvd2VscyBvdXQgb2YgeW91ciBhc3MuIEkgd2lsbCBjYXVzZSB0aGF0IHRvIGhhcHBlbiB3aXRob3V0IGxlYXZpbmcgYSBtYXJrLCBhbmQgZXZlcnkgY29wIGhlcmUgd2lsbCBzd2VhciB5b3UgZGllZCBvZiBuYXR1cmFsIGNhdXNlcy4gSW4gTWluZWNyYWZ0Lg==`
