### ISSUE TITLE
Dependencies aren't cloned properly

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#27]
Windows users shouldn't need to use `C:\msys64\mingw64\bin` as their OGRE plugins.cfg PluginFolder, it should work right out of the box.

**Comment by rjindael** [comment]
They don't -- this is only applicable on local development builds. Builds packaged by CI  already automatically bundle all relevant plugins, allowing for running out of the box. Closing for now.

**Comment by sorket** [comment]
> They don't -- this is only applicable on local development builds. Builds packaged by CI already automatically bundle all relevant plugins, allowing for running out of the box. Closing for now.

Should still be considered later in the project, then. I like the idea of someone being able to contribute by easily having something compiled & readily available as a blank slate to work from.
