### ISSUE TITLE
Major FPS drops on levels with a large amount of bricks

### ISSUE THREAD

**Issue by rjindael** [lrre-foss/rnr#32]
Our options as-is:
- Render everything in the scene graph (slow, stupid)
- Instancing (okay, but we lose a lot of eye candy)
- Static geometry (no exploding bricks)

**Comment by rjindael** [comment]
Increased load with physics, but preliminary optimization looks extremely promising (video per @floralrainfall):

https://github.com/lrre-foss/rnr/assets/59720715/87a1f016-6a4e-4552-8529-d5d8179caafa

perhaps things shall fix themselves once we add connections (lol)

**Comment by rjindael** [comment]
^^ [4f0ebdf](https://github.com/lrre-foss/rnr/commit/4f0ebdffd047e19d13e03d2434b4605f175cc331)

**Comment by rjindael** [comment]
This seems to have mostly been resolved with physics sleeping being implemented. Only rendering is left. cc @floralrainfall

**Comment by floralrainfall** [comment]
Since Render and Physics are already pretty fast, and eye candy shouldn't really be the target of a v1.0.0 release, I consider this done.
