### ISSUE TITLE
IS there a discord server or a place to discuss about this ?

### ISSUE THREAD

**Issue by ElCapor** [lrre-foss/rnr#4]
title says it all  , i'm interested in contributing to this.

**Comment by rjindael** [comment]
not as of right now, but you may use GitHub to submit contributions via pull requests

**Comment by ElCapor** [comment]
but how am i supposed to know what do you need help with ?????

**Comment by rjindael** [comment]
look at the code that isn't completed ?

**Comment by sorket** [comment]
There is a Discord server now. You may join it as it is specified in the README.
