### ISSUE TITLE
Implement core Lua (Interpreter, signal bridge)

### ISSUE THREAD

**Issue by sorket** [lrre-foss/rnr#8]

**Comment by ElCapor** [comment]
Will you build your own reflection system like roblox , or instead will make use of libs such as sol2 v3 ?

**Comment by sorket** [comment]
> Will you build your own reflection system like roblox , or instead will make use of libs such as sol2 v3 ?

I believe the idea is to build a Reflection system similar to Roblox's, par the course of #12 :-)

**Comment by floralrainfall** [comment]
Lua has been added, and is currently a WIP. This is what we have so far

- [x] Core Lua (Interpreter)
- [x] ScriptContext
- [x] Lua Scheduler
- [ ] Signals
  - [ ] Signal Bridge
- [x] ReflectionFunction
- [x] ReflectionProperty
- [ ] ReflectionEnum
- [ ] Plugin (this is optional)
