### ISSUE TITLE
Windows crashes as of 4125f87

### ISSUE THREAD

**Issue by rjindael** [lrre-foss/rnr#9]

**Comment by rjindael** [comment]
@sorket did you receive this issue?

**Comment by sorket** [comment]
If you're talking about the program exiting with code 3, then I have experienced this issue.
You have to comment out lines 26-27 in `plugins.cfg` and it should run.

```
# Plugin=Plugin_DotScene
# Plugin=Codec_Assimp
```

**Comment by rjindael** [comment]
doesn't work :( will debug later

**Comment by rjindael** [comment]
nvm, IO permissions (lol)
